title: Learning Space
description: 个人学习笔记与思考
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge
author: zhangjinglei
email: 1643200051@qq.com
github_username: day1-zhang
show_excerpts: true
minima:
  skin: classic
timezone: Asia/Shanghai
paginate: 10
paginate_path: "/page:num/"
url: "https://day1-zhang.github.io"
header_pages:
  - index.md
  - categories.md
  - tags.md
  - about.md
